<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-18T03:44:03Z" name="example suite 1" finished-at="2019-06-18T03:44:36Z" duration-ms="32537">
    <groups>
      <group name="logintests">
        <method signature="RegistrationTest.test(java.lang.String, java.lang.String)[pri:0, instance:kz.beeline.test.testcases.RegistrationTest@7ea37dbf]" name="test" class="kz.beeline.test.testcases.RegistrationTest"/>
      </group> <!-- logintests -->
    </groups>
    <test started-at="2019-06-18T03:44:03Z" name="Regression suite 1" finished-at="2019-06-18T03:44:36Z" duration-ms="32537">
      <class name="kz.beeline.test.testcases.RegistrationTest">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:kz.beeline.test.testcases.RegistrationTest@7ea37dbf]" started-at="2019-06-18T09:44:03Z" name="beforeTest" finished-at="2019-06-18T09:44:34Z" duration-ms="30258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="test(java.lang.String, java.lang.String)[pri:0, instance:kz.beeline.test.testcases.RegistrationTest@7ea37dbf]" started-at="2019-06-18T09:44:34Z" name="test" data-provider="LoginDataProvider" finished-at="2019-06-18T09:44:34Z" duration-ms="0" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:149)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:kz.beeline.test.testcases.RegistrationTest@7ea37dbf]" started-at="2019-06-18T09:44:34Z" name="afterTest" finished-at="2019-06-18T09:44:36Z" duration-ms="2217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- kz.beeline.test.testcases.RegistrationTest -->
    </test> <!-- Regression suite 1 -->
  </suite> <!-- example suite 1 -->
</testng-results>
